import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  linkBack: {
    marginTop: 10,
    marginLeft: 8,
  },
  titleLogin: {
    textAlign: 'center',
    marginTop: 59,
    marginBottom: 55,
    fontFamily: '500',
    fontSize: 24,
    color: '#fffffa',
  },
  fullBackground: {
    flex: 1,
    paddingTop: 47,
  },
  containerForm: {
    alignItems: 'flex-end',
    width: '100%',
    // height: '100%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: '#fff',
    paddingTop: 20,
    flex: 1,
    paddingLeft: 16,
    paddingRight: 16,
  },
  loginBox: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    // height: '100%',
  },
  screen: {
    flex: 1,
  },
  fullScroll: {
    flexGrow: 1,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  forgotPassword: {
    fontFamily: '400',
    fontSize: 12,
    textAlign: 'right',
    color: '#f40303',
    marginTop: 10,
    marginBottom: 25,
    alignSelf: 'flex-end',
  },
  boxCheckBox: {
    flexDirection: 'row',
    columnGap: 5,
    alignItems: 'flex-start',
    marginTop: 10,
    marginBottom: 35,
    width: 259,
  },
  textCheckBox: {
    fontFamily: '400',
    fontSize: 12,
    color: '#737373',
  },
  linkCheckBox: {
    color: '#232323',
  },
  arrowBack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowBackTitle: {
    fontFamily: '400',
    fontSize: 12,
    color: '#c8c8c8',
  },
  errorTitle: {
    color: '#f40303',
    fontFamily: '400',
    fontSize: 12,
    textAlign: 'right',
  },
  textTitle: {
    fontFamily: '400',
    fontSize: 12,
    textAlign: 'center',
    color: ' #737373',
    marginBottom: 5,
  },
  emailText: {
    color: '#232323',
  },
  cell: {
    marginTop: 35,
    marginBottom: 20,
  },
  timer: {
    fontFamily: '400',
    fontSize: 14,
    textAlign: 'center',
    color: '#232323',
    marginBottom: 25,
  },
  otpText: {
    marginTop: 20,
    fontSize: 16,
  },
  otpContainer: {
    marginBottom: 20,
    marginTop: 35,
  },
  pinCodeContainer: {
    width: 60,
    height: 55,
    backgroundColor: '#fffffa',
    borderColor: '#c8c8c8',
    borderWidth: 1,
    borderRadius: 10,
  },
  resetText: {
    fontFamily: '500',
    fontSize: 14,
    textAlign: 'center',
    color: '#5eb147',
    marginBottom: 25,
  },
  videoInstruction: {
    flex: 1,
    width: '100%',
    backgroundColor: 'white',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    paddingTop: 13,
  },
})
